sudo: true
dist: trusty

language: python

os:
    - linux

env:
    matrix:
        - TASK=nosetests

cache:
    apt: true
    directories:
        - $HOME/.cache/pip

addons:
    apt:
        packages:
            - libatlas-dev
            - libblas-dev
            - liblapack-dev
            - gfortran
            - python-numpy
            - python-scipy
            - python3-numpy
            - python3-scipy

python:
    - "2.7"
    - "3.4"
install:
    - source travis_install.sh
# command to run tests
script: nosetests